apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: claw

resources:
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - proxy-configmap.yaml
  - proxy-deployment.yaml
  - proxy-service.yaml
  - device-pairing-deployment.yaml
  - device-pairing-service.yaml
  - networkpolicy.yaml
  - ingress-networkpolicy.yaml
