apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: claw
  labels:
    app: claw
  annotations:
    haproxy.router.openshift.io/timeout: 3600s
spec:
  path: /
  to:
    kind: Service
    name: claw
    weight: 100
  port:
    targetPort: 18789
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
