---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - claw.sandbox.redhat.com
  resources:
  - claws
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - claw.sandbox.redhat.com
  resources:
  - claws/finalizers
  - nodepairingrequestapprovals/finalizers
  verbs:
  - update
- apiGroups:
  - claw.sandbox.redhat.com
  resources:
  - claws/status
  - nodepairingrequestapprovals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - claw.sandbox.redhat.com
  resources:
  - nodepairingrequestapprovals
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
